apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nginx-sc
mountOptions:
  - nfsvers=4.2
parameters:
  server: 211.183.3.99
  share:  /shared
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete