apiVersion: apps/v1
kind: Deployment
metadata: 
  name: default-deploy
  namespace: aws9d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default    # (1)Pod 작성시 이 부분(label -> app: web)이 포함되어야 함
  template:   # 여기에서 부터 Pod 작성
    metadata:
      labels:
        app: default  # 반드시 (1) 과 동일해야 함
    spec:
      containers:
        - name: aws9ctn-shop
          image: hub.aws9.pri/toytest1/aws9:default
          resources:
            requests:
              cpu: "100m"
            limits: 
              cpu: "200m"
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: default-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc-default
  namespace: aws9d
spec:
  ports:
  - name: aws9-port-default
    port: 80       # cluster-ip 의 포트 번호(type 없으면 기본은 cluster-ip )
    protocol: TCP
    targetPort: 80    # 컨테이너의 포트 
  selector:
    app: default    # Pod 의 label 을 지정해 주어야 한다!!! 
