apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: shop-keda
  namespace: aws9d
spec:
  scaleTargetRef:
    name: shop-deploy
  pollingInterval: 30
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Seoul
        start: "0 9 * * *"
        end: "0 18 * * *"
        desiredReplicas: "3"